# Generated by Django 3.2.5 on 2021-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
